version: '3'

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - node_app
  #     - flask_app
  #     - rails_app

  node_app:
    build: ./node_app
    environment:
      - DB_HOST=postgres
    ports:
      - "5002:3000"
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: your_db
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #   volumes:
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

  flask_app:
    build: ./flask_app
    ports:
      - "5001:5000"
    # depends_on:
    #   - postgres

  # rails_app:
  #   build: ./rails_app
  #   depends_on:
      # - postgres

# volumes:
#   postgres_data:

networks:
  default:
