version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend_app:/usr/share/nginx/html
    depends_on:
      - registration_app
      - flask_app
      - postgres
      - db_app
      # - rails_app

  registration_app:
    build: ./registration_app
    environment:
      - DB_HOST=postgres
    ports:
      - "5005:3000"
  #   depends_on:
  #     - postgres

  db_app:
    build: ./db_app
    environment:
      - DB_HOST=postgres
    ports:
      - "5003:3000"
    depends_on:
      - postgres
    entrypoint: ["dockerize", "-wait", "tcp://postgres:5432", "-timeout", "60s"]
    command: ["node", "app.js"]

  auth_app:
    build: ./auth_app
    environment:
      - DB_HOST=postgres
    ports:
      - "5004:3000"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  flask_app:
    build: ./flask_app
    ports:
      - "5001:5000"
    # depends_on:
    #   - postgres

  # rails_app:
  #   build: ./rails_app
  #   depends_on:
      # - postgres

# volumes:
#   postgres_data:

networks:
  default:
